application: simple-states
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

handlers:

- url: /.*
  script: test.app

libraries:
- name: django
  version: "1.2"
